Database setup
WildCodeSchool/lille-js-202003-project-special-barnacle-backend pull request #1
Opened 2020-06-30 10:27 UTC by YannYves

2020-06-30 10:30 UTC, YannYves commented
This is the database setup V1

2020-06-30 11:50 UTC, JulienMartos submitted a review, later dismissed

2020-07-06 08:32 UTC, LoicBrassart requested changes
Please correct some mistakes

2020-07-06 08:32 UTC, LoicBrassart commented on app.js
> +// app.js
Why this comm?

2020-07-06 08:32 UTC, LoicBrassart commented on app.js
> +//
Why this comm?

2020-07-06 08:32 UTC, LoicBrassart commented on connection.js
> +// connection.js
Why this comm?

2020-07-06 08:32 UTC, LoicBrassart commented on routes/formAss.js
> +  connection.query(" SELECT * FROM form_assurance", (err, results) => {
("Select *" is a bad practice)

2020-07-06 08:32 UTC, LoicBrassart commented on routes/formBanks.js
> +  connection.query(" SELECT * FROM form_banque", (err, results) => {
("Select *" is a bad practice)

2020-07-06 08:32 UTC, LoicBrassart commented on routes/partners.js
> +  connection.query(" SELECT * FROM partners", (err, results) => {
("Select  * is a bad practice")

2020-07-06 08:32 UTC, LoicBrassart commented on routes/users.js
> +  connection.query(" SELECT * FROM users", (err, results) => {
("Select * is a bad practice")

2020-07-06 13:50 UTC, LoicBrassart requested changes
Typos in requests
Did you test your work before you re-pushed ?

2020-07-06 13:50 UTC, LoicBrassart commented on routes/formAss.js
> +    " SELECT patners_a patners_b FROM form_assurance",
"patners" ? Are you sure ?

2020-07-06 13:50 UTC, LoicBrassart commented on routes/formBanks.js
> +    " SELECT parrtners_a parrtners_b  FROM form_banque",
"parrtners" ? Are you sure ?

2020-07-07 08:41 UTC, JulienMartos approved these changes

2020-07-08 08:46 UTC, LoicBrassart approved these changes
SnE

2020-07-10 12:33 UTC, merged